data_type: "real"
FPS: 30
dt: 5e-5
num_substeps: 667
dashpot_damping: 100
drag_damping: 3
base_lr: 1e-3
iterations: 250
vis_interval: 10
init_spring_Y: 3e3
init_collide_elas: 0.5
init_collide_fric: 0.3
collide_object_elas: 0.7
collide_object_fric: 0.3
radius: 0.01
max_neighbours: 20
spring_Y_min: 0
spring_Y_max: 1e5
collision_learn: true
use_graph: true
chamfer_weight: 1.0
track_weight: 1.0
acc_weight: 0.01
