data_type: "synthetic"
FPS: 10
dt: 5e-5
num_substeps: 100
dashpot_damping: 100
drag_damping: 3
base_lr: 1e-3
iterations: 500
vis_interval: 10
init_spring_Y: 3e3
collide_elas: 0.5
collide_fric: 0.3
collide_object_elas: 0.7
collide_object_fric: 0.3
object_radius: 0.1
object_max_neighbours: 20
spring_Y_min: 0
spring_Y_max: 1e5
reverse_z: false
vp_front: [-1, 0, 0.5]
vp_up: [0, 0, 1]
vp_zoom: 3
collision_dist: 0.06
collision_learn: true